#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sat Sep 12 00:18:46 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class DialogoCalibracion(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((900, 300))
        self.SelectorImagen = wx.FilePickerCtrl(self,message="Seleccione archivo",style=wx.FLP_USE_TEXTCTRL)
        self.window_1 = wx.FilePickerCtrl( self,message="Seleccione archivo",style=wx.FLP_USE_TEXTCTRL)
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=["Logaritmica", "Polinomica"], style=wx.CB_DROPDOWN)
        self.checkboxLateral = wx.CheckBox(self, wx.ID_ANY, "Correccion lateral")
        self.checkboxBackground = wx.CheckBox(self, wx.ID_ANY, "Background")
        self.Aceptar = wx.Button(self, wx.ID_ANY, "Aceptar")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Cancelar")
        
        self.resultado=['cancelar']

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.aceptar, self.Aceptar)
        self.Bind(wx.EVT_BUTTON, self.cancelar, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle(u"Calibración Manual")
        self.SetSize((900, 300))
        self.SelectorImagen.SetMinSize((400, 20))
        self.window_1.SetMinSize((400, 20))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_1 = wx.GridSizer(5, 2, 2, 2)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        labelRutaImagen = wx.StaticText(self, wx.ID_ANY, "Ruta Imagen", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(labelRutaImagen, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 2)
        grid_sizer_1.Add(self.SelectorImagen, 1, wx.ALIGN_CENTER, 0)
        labelRutaDatosCalibracion = wx.StaticText(self, wx.ID_ANY, "Ruta datos de calibracion")
        grid_sizer_1.Add(labelRutaDatosCalibracion, 0, wx.ALIGN_CENTER | wx.ALL, 0)
        grid_sizer_1.Add(self.window_1, 1, wx.ALIGN_CENTER, 0)
        labelTipo = wx.StaticText(self, wx.ID_ANY, "Tipo de calibracion", style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(labelTipo, 1, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.combo_box_1, 0, wx.ALIGN_CENTER | wx.ALL | wx.SHAPED, 0)
        labelCorecciones = wx.StaticText(self, wx.ID_ANY, "Correcciones")
        grid_sizer_1.Add(labelCorecciones, 0, wx.ALIGN_CENTER, 0)
        sizer_1.Add(self.checkboxLateral, 1, wx.ALL | wx.EXPAND, 1)
        sizer_1.Add(self.checkboxBackground, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_1, 1, wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE | wx.SHAPED, 0)
        grid_sizer_1.Add(self.Aceptar, 0, wx.ALIGN_RIGHT | wx.ALL, 1)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        self.SetSizer(grid_sizer_1)
        self.Layout()
        # end wxGlade

    def aceptar(self, event):  # wxGlade: MyDialog.<event_handler>
        self.resultado=[]
        self.resultado.append(self.SelectorImagen.GetPath())
        self.resultado.append(self.window_1.GetPath())
        self.resultado.append(self.combo_box_1.GetStringSelection())
        self.resultado.append(self.checkboxLateral.GetValue())
        self.resultado.append(self.checkboxBackground.GetValue())
        #event.Skip()
        print(self.resultado)
        self.Close()

    def cancelar(self, event):  # wxGlade: MyDialog.<event_handler>
        self.Close()
        #event.Skip()

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = DialogoCalibracion(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
