#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Thu Nov 12 23:01:15 2020
#

import numpy as np
import wx
import wx.lib.agw.aui as aui
import wx.lib.mixins.inspection as wit

from dialogoCalibracionAlternativo import DialogoCalibracion
from dialogoSeleccionDosis import *
from claseCalibracion import *
from claseDialogoBackground import *
from panelSeleccionDosis import *
from dialogoMapaDosis import *
from filtradoImagenes import filtrar_imagen
from panelMapaDosis2 import *
from panelMapaDosis1 import *
from dialogoComparacionPlan import *
from panelComparacionAPlan import *
from imagenMatplotlibLibre import *

import matplotlib as mpl
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar

import tifffile as tiff
from skimage.transform import rescale

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

def leerDosis(nombre_archivo):
    dosis=np.genfromtxt(nombre_archivo)
    return dosis.tolist()

def poner_imagen_en_punto(imgPoner,tamanoGrande,puntoEnGrande,puntoEnPoner):
    resp=np.zeros(tamanoGrande)
    x=imgPoner.shape[0]
    y=imgPoner.shape[1]
    if x%2==0:
        cor=0
    else:
        cor=1
    if y%2==0:
        cory=0
    else:
        cory=1 
    resp[puntoEnGrande[0]-int(x/2)+0:puntoEnGrande[0]+int(x/2)+cor+0,puntoEnGrande[1]-int(y/2)+0:puntoEnGrande[1]+int(x/2)+cory+0]=imgPoner
    return resp
    
class Calibracion():
    def __init__(self,figuras,nombresArchivos,panelDosis):
        self.panelesMatplot=figuras
        self.nombresArchivos=nombresArchivos
        self.panelDosis=panelDosis
        
        self.fondoCero=[]
        self.fondoNegro=[]

class MapaDeDosis():
    def __init__(self,imagenOriginal,mapaCalculado):
        self.imagenOriginal=imagenOriginal
        self.mapaCalculado=mapaCalculado

class ComparacionAPlan():
    def __init__(self,imagenEscan,imagenCalculada):
        self.imScan=imagenEscan
        self.imCalc=imagenCalculada
        
        
class ImagenCuadernoMatplotlib(wx.Panel):
    def __init__(self, parent, id=-1, dpi=None, **kwargs):
        wx.Panel.__init__(self, parent, id=id, **kwargs)
        self.figure = mpl.figure.Figure(dpi=dpi)
        #self.figure.gca().axis('off')
        self.axA=self.figure.gca()
        self.canvas = FigureCanvas(self, -1, self.figure)
        #self.toolbar = NavigationToolbar(self.canvas)
        #self.toolbar.Realize()
        self.identificador=0
        self.tipo=''
        self.rutaImagen=''
        self.arrayIma=''
        
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.canvas, 1, wx.EXPAND)
        #sizer.Add(self.toolbar, 0, wx.LEFT | wx.EXPAND)
        self.SetSizer(sizer)
        self.Fit()


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1366, 741))
        self.notebookImagenes = aui.AuiNotebook(self, wx.ID_ANY)
        
        self.paginas=[]
        self.paginas.append(ImagenCuadernoMatplotlib(self.notebookImagenes))
        self.paginaActual=self.paginas[0]
        self.arayActual=[]
        self.araySinIrra=[]
        self.araySinLuz=[]
        
        self.configuracion={"BitCanal":16,"Filtros":['mediana'],"ppi":100}
        
        
        self.arbolArchivos = wx.TreeCtrl(self, wx.ID_ANY,style=wx.TR_LINES_AT_ROOT)
        self.panelVariable = wx.Panel(self, wx.ID_ANY)
        self.calibraciones=[]
        self.mapasDeDosis=[]
        self.comparacionesAPlan=[]
        self.numeroPags=0
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Guardar...", "")
        self.Bind(wx.EVT_MENU, self.guardar, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Abrir...", "")
        self.Bind(wx.EVT_MENU, self.abrir, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Cerrar", "")
        self.Bind(wx.EVT_MENU, self.cerrar, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Archivo")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Generar calibracion", "")
        self.Bind(wx.EVT_MENU, self.calibrarNueva, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Calibracion")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Generar mapa", "")
        self.Bind(wx.EVT_MENU, self.mapaNuevo, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Realizar comparacion", "")
        self.Bind(wx.EVT_MENU, self.compararMapas, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Mapas de dosis")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Promediador", "")
        self.Bind(wx.EVT_MENU, self.promediarImagenes, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Apilar", "")
        self.Bind(wx.EVT_MENU, self.apilarImagenes, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Filtrar", "")
        self.Bind(wx.EVT_MENU, self.filtrarImagenes, id=item.GetId())
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Configuracion", "")
        self.Bind(wx.EVT_MENU, self.cambiarConfiguracion, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Herramientas")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.FilmQADog_statusbar = self.CreateStatusBar(1, wx.STB_DEFAULT_STYLE)
        
        self.Bind(aui.EVT_AUINOTEBOOK_PAGE_CHANGED,self.cambioPagina,self.notebookImagenes)

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("FilmQADog")
        self.FilmQADog_statusbar.SetStatusWidths([-1])
        
        self.raiz=self.arbolArchivos.AddRoot("FilmQADog")
        ident=self.arbolArchivos.AppendItem(self.raiz,"Bienvenido")
        self.arbolArchivos.ExpandAll()

        # statusbar fields
        FilmQADog_statusbar_fields = ["FilmQADog_statusbar"]
        for i in range(len(FilmQADog_statusbar_fields)):
            self.FilmQADog_statusbar.SetStatusText(FilmQADog_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.notebookImagenes, 2, wx.EXPAND, 0)
        self.sizer_2.Add(self.arbolArchivos, 1, wx.EXPAND, 0)
        self.sizerPanel=self.sizer_2.Add(self.panelVariable, 1, wx.EXPAND, 0)
        sizer_1.Add(self.sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        
        
        self.notebookImagenes.AddPage(self.paginas[0], "Bienvenido")
        figInicial=self.paginas[0].figure
        a1=figInicial.gca()
        im = tiff.imread('filmQAPerro.tif')
        self.arayActual=im
        a1.imshow(im)
        self.Layout()
        # end wxGlade

    def calibrarNueva(self, event):  # wxGlade: MyFrame.<event_handler>
        dialogoCalibracion=DialogoCalibracion(self)
        dialogoCalibracion.ShowModal()
        if dialogoCalibracion.resultado!='cancelar':
            self.arayActual=tiff.imread(dialogoCalibracion.nombreArchivos[0])
            self.araySinIrra=0*self.arayActual
            self.araySinLuz=0*self.arayActual
            
            if(dialogoCalibracion.background):
                dialogoBackground=DialogoBackground(self)
                dialogoBackground.ShowModal()
                fon=False
                if dialogoBackground.resultado[0]!='cancelar' and dialogoBackground.resultado[0]!='':
                    self.araySinIrra=tiff.imread(dialogoBackground.resultado[0])
                    fon=True
                if(dialogoBackground.resultado[0]!='cancelar' and dialogoBackground.resultado[1]!=''):
                    self.araySinLuz=tiff.imread(dialogoBackground.resultado[1])
                    if fon:
                        self.araySinIrra=self.araySinIrra-self.araySinLuz
                        
            if(dialogoCalibracion.filtrar):
                self.arayActual=filtrar_imagen(self.arayActual,self.configuracion["Filtros"])
                self.araySinIrra=filtrar_imagen(self.araySinIrra,self.configuracion["Filtros"])
            
            calibracionActual=Calibracion([],[],[])
            rez=self.arbolArchivos.AppendItem(self.raiz,"Calibracion "+str(len(self.calibraciones)+1))
            for nombreImagen in dialogoCalibracion.nombreArchivos:    
                self.paginas.append(ImagenCuadernoMatplotlib(self.notebookImagenes))
                self.notebookImagenes.AddPage(self.paginas[-1], "Calibracion "+str(len(self.calibraciones)+1))
                self.numeroPags=self.numeroPags+1
                self.paginas[-1].identificador=self.numeroPags
                self.paginas[-1].tipo='cali'
                self.paginas[-1].rutaImagen=nombreImagen
                nuem=self.notebookImagenes.GetPageCount()-1
                self.notebookImagenes.SetSelection(nuem)
                figActual=self.paginas[-1].figure
                self.paginaActual=self.paginas[-1]
                a1=figActual.gca()
                self.arayActual=tiff.imread(nombreImagen)
                self.paginas[-1].arrayIma=self.arayActual
                #self.arayActual=self.arayActual-self.araySinLuz
                if(dialogoCalibracion.filtrar):
                    self.paginas[-1].arrayIma=filtrar_imagen(self.arayActual,self.configuracion["Filtros"])
                    self.arayActual=self.paginas[-1].arrayIma
                escalado=(self.arayActual/2**self.configuracion["BitCanal"])*255
                a1.imshow(escalado.astype(int)) 
                calibracionActual.panelesMatplot.append(self.paginas[-1])
                calibracionActual.nombresArchivos.append(nombreImagen)
                self.arbolArchivos.AppendItem(rez,"Imagen "+str(len(calibracionActual.nombresArchivos)))
                
                
            dosisReal=leerDosis(dialogoCalibracion.nombreArchivoDos)
            
            
            self.panelVariable=PanelSeleccionDosis(self,dosis=dosisReal,canal=dialogoCalibracion.tipoCanal,curva=dialogoCalibracion.tipoCurva)
            calibracionActual.panelDosis=self.panelVariable
            calibracionActual.fondoCero=self.araySinIrra
            calibracionActual.fondoNegro=self.araySinLuz
            self.calibraciones.append(calibracionActual)
            self.sizer_2.Remove(1)
            self.sizer_2.Add(self.panelVariable, 1, wx.EXPAND, 0)
            
            
            self.Layout()
        event.Skip()

    def abrir(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'abrir' not implemented!")
        event.Skip()

    def cerrar(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'cerrar' not implemented!")
        event.Skip()

    def guardar(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'calibrar' not implemented!")
        event.Skip()

    def mapaNuevo(self, event):  # wxGlade: MyFrame.<event_handler>
        dialMapa=DialogoMapaDosis(self)
        dialMapa.ShowModal()
        if dialMapa.resultado=='cancelar':
            return 
        mapaNe=MapaDeDosis([],[])  
         
        datosCalib=leer_Calibracion(dialMapa.rutaCalibracion)
        image=tiff.imread(dialMapa.rutaImagen)
        self.araySinIrra=0*image
        ceR=self.araySinIrra[:,:,0]+datosCalib["Ceros"][0][0]
        ceG=self.araySinIrra[:,:,1]+datosCalib["Ceros"][1][0]
        ceB=self.araySinIrra[:,:,2]+datosCalib["Ceros"][2][0]
        self.araySinIrra=np.dstack((ceR,ceG,ceB))*(2**self.configuracion["BitCanal"])
        self.araySinLuz=0*image
        
        
        
        
        if dialMapa.corrBackground:
            dialogoBackground=DialogoBackground(self)
            dialogoBackground.ShowModal()
            fon=False
            
            if dialogoBackground.resultado[0]!='cancelar' and dialogoBackground.resultado[0]!='':
                self.araySinIrra=tiff.imread(dialogoBackground.resultado[0])
                fon=True
            if(dialogoBackground.resultado[0]!='cancelar' and dialogoBackground.resultado[1]!=''):
                self.araySinLuz=tiff.imread(dialogoBackground.resultado[1])
                image=image-self.araySinLuz
                if fon:
                    self.araySinIrra=self.araySinIrra-self.araySinLuz
            
        if dialMapa.filtrar:
            image=filtrar_imagen(image,self.configuracion["Filtros"])
            self.araySinIrra=filtrar_imagen(self.araySinIrra,self.configuracion["Filtros"])
            
        self.arayActual=image
        self.paginas.append(ImagenCuadernoMatplotlib(self.notebookImagenes))
        self.notebookImagenes.AddPage(self.paginas[-1], "Mapa de dosis "+str(len(self.mapasDeDosis)+1))
        self.numeroPags=self.numeroPags+1
        self.paginas[-1].identificador=self.numeroPags
        self.paginas[-1].tipo='md1'
        self.paginas[-1].rutaImagen=dialMapa.rutaImagen
        nuem=self.notebookImagenes.GetPageCount()-1
        self.notebookImagenes.SetSelection(nuem)
        figActual=self.paginas[-1].figure
        self.paginaActual=self.paginas[-1]
        a1=figActual.gca()
        self.paginas[-1].arrayIma=self.arayActual
        escalado=(self.arayActual/2**self.configuracion["BitCanal"])*255
        a1.imshow(escalado.astype(int))
        

        
        self.sizer_2.Remove(1)
        self.panelVariable=PanelMapaDosis1(self,dialMapa.rutaCalibracion)
        self.sizer_2.Add(self.panelVariable, 1, wx.EXPAND, 0)
        self.Layout()
        event.Skip()

    def compararMapas(self, event):  # wxGlade: MyFrame.<event_handler>
        dialComparar=DialogoComparacionPlan(self)
        dialComparar.ShowModal()
        if dialComparar.resultado=='cancelar':
            return
        dicomPlan=pydicom.dcmread(dialComparar.rutaPlan)
        dicomEscan=pydicom.dcmread(dialComparar.rutaEscan)
        reescaldo=np.array(dicomPlan.PixelSpacing)/np.array(dicomEscan.PixelSpacing)
        arrayPlan=rescale(dicomPlan.pixel_array,reescaldo,anti_aliasing=False)
        print(arrayPlan.shape)
        centroEscan=int(dicomEscan.pixel_array.shape[0]/2),int(dicomEscan.pixel_array.shape[1]/2)
        arrayPlanAjus=poner_imagen_en_punto(arrayPlan,dicomEscan.pixel_array.shape,centroEscan,(0,0))
        
        
        rez=self.arbolArchivos.AppendItem(self.raiz,"Comparacion a plan  "+str(len(self.comparacionesAPlan)+1))
        self.arayActual=[arrayPlanAjus,dicomEscan.pixel_array]
        self.paginas.append(ImagenCuadernoMatplotlib(self.notebookImagenes))
        self.notebookImagenes.AddPage(self.paginas[-1], "Comparacion a plan "+str(len(self.comparacionesAPlan)+1))
        self.numeroPags=self.numeroPags+1
        self.paginas[-1].identificador=self.numeroPags
        self.paginas[-1].tipo='compa'
        self.paginaActual=self.paginas[-1]
        nuem=self.notebookImagenes.GetPageCount()-1
        self.notebookImagenes.SetSelection(nuem)
        figActual=self.paginas[-1].figure
        self.paginaActual=self.paginas[-1]
        a1=figActual.gca()
        
        """
        arrayPlan=arrayPlanAjus/np.max(arrayPlanAjus)
        arrayEscan=dicomEscan.pixel_array*dicomEscan.DoseGridScaling/7.00
        """
        arraPlan=arrayPlanAjus*dicomPlan.DoseGridScaling
        arrayEscan=dicomEscan.pixel_array*dicomEscan.DoseGridScaling
        
        self.arayActual=[arrayPlan,arrayEscan]
        self.paginas[-1].arrayIma=[arrayPlan,arrayEscan]
        
        
        self.alpha=0.5
        
        
        a1.imshow((1.0-self.alpha)*arrayPlan+self.alpha*arrayEscan,cmap=plt.cm.gray)
        self.axR=self.paginaActual.figure.add_axes([0.25, .03, 0.50, 0.02])
        self.alp = Slider(self.axR, 'Alpha', 0, 1, valinit=0.5, valstep=0.01)
        def update(val):
            iv=self.alp.val
            self.paginaActual.axA.clear()
            self.paginaActual.axA.imshow((1.0-iv)*arrayPlan+iv*arrayEscan,cmap=plt.cm.gray)
            self.paginaActual.figure.canvas.draw_idle()
        self.alp.on_changed(update) 
        
        self.panelVariable=PanelComparacionAPlan(self)
        self.sizer_2.Remove(1)
        self.sizer_2.Add(self.panelVariable, 1, wx.EXPAND, 0)
        self.Layout()
        event.Skip()

    def promediarImagenes(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'promediarImagenes' not implemented!")
        event.Skip()

    def apilarImagenes(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'apilarImagenes' not implemented!")
        event.Skip()

    def filtrarImagenes(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'filtrarImagenes' not implemented!")
        event.Skip()

    def cambiarConfiguracion(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'cambiarConfiguracion' not implemented!")
        event.Skip()
    def cambioPagina(self,event):
        print('cambioPagina')
        pestana=self.notebookImagenes.GetCurrentPage()
        if pestana.tipo=='cali':
            for cals in self.calibraciones:
                for fisa in cals.panelesMatplot:
                    if fisa.identificador==pestana.identificador:
                        self.arayActual=fisa.arrayIma
                        self.araySinIrra=cals.fondoCero
                        self.araySinLuz=cals.fondoNegro
                        self.paginaActual=fisa
                        self.panelVariable=cals.panelDosis
                        print(self.panelVariable.R)
                        break
        
                      
        self.sizer_2.Remove(1)
        self.sizer_2.Add(self.panelVariable, 1, wx.EXPAND, 0)
        self.Layout()
                        
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.FilmQADog = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.FilmQADog)
        self.FilmQADog.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
